# 开启后，pRest不使用jwt认证
debug = true

[app]
name = "GZHU-Pi"
version = "2.0"
mode = "debug"
log_level = "debug"
logfile = "/tmp/gzhupi/log.log"

port = 9000
prest = true
init_models = true

[secret]
jwt = "jwt_secret"

[rpc]
addr = "localhost:8080"
token = ""

[kafka]
enabled = false
broker = ["localhost:9092"]

[db]
type = "postgres"
host = "localhost"
port = "5432"
user = "postgres"
password = "postgres"
dbname = "postgres"
sslmode = "disable"

[redis]
host = "localhost"
port = "6379"
password = ""

[weixin]
enabled = false
token = ""
ase_key = ""
app_id = ""
secret = ""
min_app_id = ""
min_app_secret = ""

# 腾讯云cos
[cos]
enabled = false
secret_id = ""
secret_key = ""

# face++ api
[facepp]
enabled = false
api_key = ""
api_secret = ""


# ================================================
# 以下是pRest的配置 Documents https://postgres.rest/
# ================================================

# enabling debug mode will disable JWT authorization
debug = true

[http]
port = 9000

[queries]
location = "queries"

[jwt]
key = "secret"
algo = "HS256"

[pg]
host = "localhost"
user = "postgres"
pass = "postgres"
port = 5432
database = "postgres"
## or used cloud factor
# URL = "postgresql://postgres:postgres@localhost/postgres/?sslmode=disable"

[ssl]
mode = "disable"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

[cors]
alloworigin = ["*"]

[access]
restrict = false # can access only the tables listed below

[[access.tables]]
name = "v_user"
permissions = ["read"]
fields = ["*"]

[[access.tables]]
name = "t_user"
permissions = ["write"]
fields = ["id"]
