app:
  name: GZHU-Pi
  version: '1.1'
  mode: debug
  log_level: debug
  logfile: /tmp/gzhupi/log.log


rpc:
  addr: ifeel.vip:7201
  tocken: 1234


db:
  type: postgre
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  sslmode: disable


redis:
  host: 127.0.0.1
  port: '6379'
  password: foobar

weixin:
  path: /
  token: foobar
  app_id: 12345678
  secret: 12345678