version: "3.6"

networks:
  gzhupi-net:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/gzhupi:/tmp/gzhupi
    environment:
      - GZHUPI_DB_HOST=gzhu-pi-db
      - GZHUPI_DB_PORT=5432
      - GZHUPI_DB_USER=postgres
      - GZHUPI_DB_PASSWORD=postgres
      - GZHUPI_DB_DBNAME=postgres
      - GZHUPI_DB_SSLMODE=disable
      - TZ=Asia/Shanghai
    depends_on:
      - pgdb

  pgdb:
    image: postgres:alpine
    container_name: gzhu-pi-db
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 5432:5432
    environment:
      - PGTZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

#  prest:
#    image: prest/prest
#    container_name: gzhu-pi-prest
#    restart: always
#    networks:
#      - gzhupi-net
#    ports:
#      - 3010:3010
#    volumes:
#      - $PWD/config.toml:/prest.toml
#    environment:
#      # docker环境变量会覆盖prest配置文件对应值
#      - PREST_HTTP_PORT=3010
#      - PREST_PG_HOST=gzhu-pi-db
#      - PREST_PG_USER=postgres
#      - PREST_PG_PASS=postgres
#      - PREST_PG_DATABASE=postgres
#      - PREST_PG_PORT=5432
#      # - PREST_JWT_KEY
#      # - PREST_JWT_ALGO
#    depends_on:
#      - pgdb
