version: "3.6"

networks:
  gzhupi-net:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/gzhupi:/home/log
    environment:
      - GZHUPI_SECRET_JWT=${GZHUPI_SECRET_JWT}
      - GZHUPI_RPC_ADDR=${GZHUPI_RPC_ADDR}
      - GZHUPI_DB_HOST=${GZHUPI_DB_HOST}
      - GZHUPI_DB_PORT=${GZHUPI_DB_PORT}
      - GZHUPI_DB_USER=${GZHUPI_DB_USER}
      - GZHUPI_DB_PASSWORD=${GZHUPI_DB_PASSWORD}
      - GZHUPI_DB_DBNAME=${GZHUPI_DB_DBNAME}
      - GZHUPI_DB_SSLMODE=${GZHUPI_DB_SSLMODE}
      - GZHUPI_REDIS_HOST=${GZHUPI_REDIS_HOST}
      - GZHUPI_REDIS_PORT=${GZHUPI_REDIS_PORT}
      - GZHUPI_REDIS_PASSWORD=${GZHUPI_REDIS_PASSWORD}
      - GZHUPI_APP_INIT_MODELS=false
      - TZ=Asia/Shanghai

