version: "3.6"

networks:
  gzhupi-net:

volumes:
  gzhupi_pgdb:
  gzhupi_redis:
  gzhupi_kafka:
  gzhupi_zookeeper:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/gzhupi:/tmp/gzhupi
    environment:
      # 此处的环境变量会覆盖配置文件中的对应配置
      - GZHUPI_SECRET_JWT=jwt_secret
      - GZHUPI_RPC_ADDR=gzhu-pi-tesseract-rpc:8080
      - GZHUPI_RPC_TOKEN=

      - GZHUPI_KAFKA_ENABLED=true
      - GZHUPI_KAFKA_BROKER=gzhu-pi-kafka:9092

      - GZHUPI_DB_HOST=gzhu-pi-db
      - GZHUPI_DB_PORT=5432
      - GZHUPI_DB_USER=postgres
      - GZHUPI_DB_PASSWORD=postgres
      - GZHUPI_DB_DBNAME=postgres
      - GZHUPI_DB_SSLMODE=disable

      - GZHUPI_REDIS_HOST=gzhu-pi-redis
      - GZHUPI_REDIS_PORT=6379
      - GZHUPI_REDIS_PASSWORD=

      - GZHUPI_APP_INIT_MODELS=true
      - TZ=Asia/Shanghai

    depends_on:
      - pgdb
      - kafka

  pgdb:
    image: postgres:alpine
    container_name: gzhu-pi-db
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 5432:5432
    environment:
      - PGTZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - gzhupi_pgdb:/var/lib/postgresql/data

  rejson:
    image: redislabs/redisjson2
    container_name: gzhu-pi-redis
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 6379:6379
    volumes:
      - gzhupi_redis:/data

  # 验证码识别 rpc 服务
  tesseract:
    image: zhenshaw/tesseract:rpc
    container_name: gzhu-pi-tesseract-rpc
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 8080:8080


  # zookeeper及kafka消息队列
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: gzhu-pi-zookeeper
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 2181:2181
    volumes:
      - gzhupi_zookeeper:/data

  kafka:
    image: wurstmeister/kafka
    container_name: gzhu-pi-kafka
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=gzhu-pi-zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=gzhu-pi-kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_HEAP_OPTS="-Xms128M"
    volumes:
      - gzhupi_kafka:/kafka
    depends_on:
      - zookeeper