version: '3.6'

networks:
  gzhupi-net:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/gzhupi:/tmp/gzhupi

    environment:
      - GZHUPI_DB_HOST=ifeel.vip
      - GZHUPI_DB_PORT=5432
      - GZHUPI_DB_USER=gzhupi
      - GZHUPI_DB_PASSWORD=gzhupi
      - GZHUPI_DB_DBNAME=gzhupi
      - GZHUPI_DB_SSLMODE=require
      - TZ=Asia/Shanghai
