version: '3.6'

networks:
  gzhupi-net:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/log:/tmp/log
