version: "3.6"

networks:
  gzhupi-net:

volumes:
  gzhupi_pgdb:
  gzhupi_redis:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gzhu-pi
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 9000:9000
    volumes:
      - /tmp/gzhupi:/tmp/gzhupi
    environment:
      # 此处的环境变量会覆盖配置文件中的对应配置
      - GZHUPI_SECRET_JWT=jwt_secret
      - GZHUPI_RPC_ADDR=gzhu-pi-rpc:7201
      - GZHUPI_DB_HOST=gzhu-pi-db
      - GZHUPI_DB_PORT=5432
      - GZHUPI_DB_USER=postgres
      - GZHUPI_DB_PASSWORD=postgres
      - GZHUPI_DB_DBNAME=postgres
      - GZHUPI_DB_SSLMODE=disable
      - TZ=Asia/Shanghai
      - GZHUPI_REDIS_HOST=gzhu-pi-redis
      - GZHUPI_REDIS_PORT=6379
      - GZHUPI_REDIS_PASSWORD=
    depends_on:
      - pgdb

  pgdb:
    image: postgres:alpine
    container_name: gzhu-pi-db
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 5432:5432
    environment:
      - PGTZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - gzhupi_pgdb:/var/lib/postgresql/data

  rejson:
    image: redislabs/redisjson2
    container_name: gzhu-pi-redis
    restart: always
    networks:
      - gzhupi-net
    ports:
      - 6379:6379
    volumes:
      - gzhupi_redis:/data

  rpc:
    build:
      context: ./rpc
      dockerfile: Dockerfile
    container_name: gzhu-pi-rpc
    restart: always
    ports:
      - 7201:7201
    networks:
      - gzhupi-net